function seedPocFixtureData_() {
  const now = new Date();
  const importId = 'imp_fixture_202606';
  appendObjects_('IMPORT_BATCH', [{ tenant_id: 'klinik_001', clinic_id: 'clinic_001', import_id: importId, source_system: 'fixture', import_method: 'upload_excel', period_start: '2026-06-01', period_end: '2026-06-30', status: 'imported', data_status: 'complete', started_at: now, completed_at: now, created_by: 'system', notes: 'POC fixture' }]);
  appendObjects_('PENDAPATAN', [
    { tenant_id: 'klinik_001', clinic_id: 'clinic_001', revenue_id: 'rev_001', transaction_id: 'TRX001', import_id: importId, source_row_id: 'fixture_1', visit_id: 'V001', doctor_id: 'doc_d001', poli_id: 'poli_p001', transaction_date: '2026-06-01', revenue_type: 'tindakan', item_code: 'CONS', item_name: 'Konsultasi', quantity: 1, unit_price: 250000, gross_amount: 250000, discount_amount: 0, net_amount: 250000, paid_amount: 250000, receivable_amount: 0, payment_method: 'cash', payer_type: 'umum', cashier: 'admin', status: 'paid', trace_status: 'traceable', created_at: now },
    { tenant_id: 'klinik_001', clinic_id: 'clinic_001', revenue_id: 'rev_002', transaction_id: 'TRX002', import_id: importId, source_row_id: 'fixture_2', visit_id: 'V002', doctor_id: 'doc_d002', poli_id: 'poli_p001', transaction_date: '2026-06-01', revenue_type: 'tindakan', item_code: 'CONS', item_name: 'Konsultasi', quantity: 1, unit_price: 300000, gross_amount: 300000, discount_amount: 0, net_amount: 300000, paid_amount: 300000, receivable_amount: 0, payment_method: 'cash', payer_type: 'umum', cashier: 'admin', status: 'paid', trace_status: 'traceable', created_at: now },
    { tenant_id: 'klinik_001', clinic_id: 'clinic_001', revenue_id: 'rev_003', transaction_id: 'TRX003', import_id: importId, source_row_id: 'fixture_3', visit_id: 'V003', doctor_id: 'doc_d001', poli_id: 'poli_p001', transaction_date: '2026-06-02', revenue_type: 'bpjs', item_code: 'BPJS', item_name: 'Klaim BPJS', quantity: 1, unit_price: 750000, gross_amount: 750000, discount_amount: 0, net_amount: 750000, paid_amount: 0, receivable_amount: 750000, payment_method: 'bpjs', payer_type: 'bpjs', cashier: 'admin', status: 'partial', trace_status: 'traceable', created_at: now },
    { tenant_id: 'klinik_001', clinic_id: 'clinic_001', revenue_id: 'rev_004', transaction_id: 'TRX004', import_id: importId, source_row_id: 'fixture_4', visit_id: 'V004', doctor_id: 'doc_d003', poli_id: 'poli_p002', transaction_date: '2026-06-02', revenue_type: 'resep', item_code: 'MED001', item_name: 'Obat A', quantity: 1, unit_price: 150000, gross_amount: 150000, discount_amount: 0, net_amount: 150000, paid_amount: 150000, receivable_amount: 0, payment_method: 'cash', payer_type: 'umum', cashier: 'admin', status: 'paid', trace_status: 'traceable', created_at: now },
    { tenant_id: 'klinik_001', clinic_id: 'clinic_001', revenue_id: 'rev_005', transaction_id: 'TRX005', import_id: importId, source_row_id: 'fixture_5', visit_id: 'V005', doctor_id: 'doc_d001', poli_id: 'poli_p001', transaction_date: '2026-06-03', revenue_type: 'lab', item_code: 'LAB', item_name: 'Lab Panel', quantity: 1, unit_price: 500000, gross_amount: 500000, discount_amount: 0, net_amount: 500000, paid_amount: 500000, receivable_amount: 0, payment_method: 'cash', payer_type: 'umum', cashier: 'admin', status: 'paid', trace_status: 'traceable', created_at: now },
  ]);
  appendObjects_('BIAYA', [
    { tenant_id: 'klinik_001', clinic_id: 'clinic_001', expense_id: 'exp_001', import_id: importId, source_row_id: 'fixture_exp_1', expense_date: '2026-06-01', expense_category: 'jasa_dokter', expense_name: 'Jasa dokter', account_id: 'coa_doctor_fee', amount: 220000, payment_method: 'transfer', vendor_name: '', related_visit_id: '', related_item_code: '', cost_type: 'variable', allocation_target: 'doctor', allocation_id: '', status: 'paid', trace_status: 'traceable', created_at: now },
    { tenant_id: 'klinik_001', clinic_id: 'clinic_001', expense_id: 'exp_002', import_id: importId, source_row_id: 'fixture_exp_2', expense_date: '2026-06-02', expense_category: 'hpp_obat', expense_name: 'HPP obat', account_id: 'coa_cogs', amount: 90000, payment_method: 'transfer', vendor_name: 'Supplier', related_visit_id: 'V004', related_item_code: 'MED001', cost_type: 'cogs', allocation_target: 'clinic', allocation_id: 'clinic_001', status: 'paid', trace_status: 'traceable', created_at: now },
    { tenant_id: 'klinik_001', clinic_id: 'clinic_001', expense_id: 'exp_003', import_id: importId, source_row_id: 'fixture_exp_3', expense_date: '2026-06-03', expense_category: 'operasional', expense_name: 'Gaji dan sewa', account_id: 'coa_opex', amount: 1750000, payment_method: 'transfer', vendor_name: '', related_visit_id: '', related_item_code: '', cost_type: 'fixed', allocation_target: 'clinic', allocation_id: 'clinic_001', status: 'paid', trace_status: 'traceable', created_at: now },
  ]);
  appendObjects_('KUNJUNGAN', [1, 2, 3, 4, 5].map(i => ({ tenant_id: 'klinik_001', clinic_id: 'clinic_001', visit_id: `V00${i}`, source_visit_id: `V00${i}`, import_id: importId, source_row_id: `fixture_visit_${i}`, visit_date: `2026-06-0${Math.min(i, 3)}`, registration_time: '', patient_ref: `patient_hash_00${i}`, patient_type: i === 3 ? 'bpjs' : 'umum', payer_type: i === 3 ? 'bpjs' : 'cash', doctor_id: i === 2 ? 'doc_d002' : 'doc_d001', poli_id: 'poli_p001', service_category: 'rawat_jalan', service_name: 'Kunjungan', status: 'completed', data_status: 'complete', created_at: now, updated_at: now })));
}

function seedPhase1FixtureData_() {
  return seedPocFixtureData_();
}
